create table if not exists "public"."suggestions" (
    "id" bigint generated by default as identity not null,
    "document_id" bigint not null,
    "prompt" text not null,
    "text" text not null,
    "raw_data" jsonb,
    "created_at" timestamp with time zone default now()
);


CREATE UNIQUE INDEX if not exists suggestions_pkey ON public.suggestions USING btree (id);

alter table "public"."suggestions" add constraint "suggestions_pkey" PRIMARY KEY using index "suggestions_pkey";

alter table "public"."suggestions" add constraint "suggestions_document_id_fkey" FOREIGN KEY (document_id) REFERENCES documents(id) not valid;

alter table "public"."suggestions" validate constraint "suggestions_document_id_fkey";


