drop policy "Can only view own subs data." on "public"."subscriptions";

alter table "public"."subscriptions" drop constraint "subscriptions_price_id_fkey";

alter table "public"."subscriptions" drop constraint "subscriptions_user_id_fkey";

alter table "public"."subscriptions" drop constraint "subscriptions_pkey";

drop index if exists "public"."subscriptions_pkey";

drop table "public"."subscriptions";



create table "public"."subscriptions" (
    "id" bigint generated by default as identity not null,
    "subscription_id" integer,
    "status" text,
    "email" text,
    "paddle_user_id" bigint,
    "marketing_consent" text,
    "cancel_url" character varying,
    "update_url" character varying,
    "subscription_plan_id" integer,
    "next_bill_date" date,
    "passthrough" character varying,
    "currency" character varying,
    "checkout_id" text,
    "source" text,
    "linked_subscriptions" text,
    "custom_data" text,
    "quantity" bigint,
    "unit_price" text,
    "created_at" timestamp with time zone default now(),
    "country" text,
    "earnings" numeric,
    "plan_name" text,
    "fee" text,
    "sale_gross" text,
    "coupon" text,
    "receipt_url" text,
    "instalments" text,
    "next_payment_amount" text,
    "balance_gross" text,
    "balance_fee" text,
    "balance_earnings" text,
    "balance_currency" text,
    "event_time" timestamp without time zone
);


CREATE UNIQUE INDEX subscriptions_pkey ON public.subscriptions USING btree (id);

CREATE UNIQUE INDEX subscriptions_subscription_id_unique_constraint ON public.subscriptions USING btree (subscription_id);

alter table "public"."subscriptions" add constraint "subscriptions_pkey" PRIMARY KEY using index "subscriptions_pkey";

alter table "public"."subscriptions" add constraint "subscriptions_subscription_id_unique_constraint" UNIQUE using index "subscriptions_subscription_id_unique_constraint";


