create table "public"."integrations" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid,
    "name" text not null,
    "type" text not null,
    "host" text not null,
    "username" text not null,
    "password" text,
    "created_at" timestamp with time zone default now()
);


CREATE UNIQUE INDEX integrations_pkey ON public.integrations USING btree (id);

alter table "public"."integrations" add constraint "integrations_pkey" PRIMARY KEY using index "integrations_pkey";

alter table "public"."integrations" add constraint "integrations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."integrations" validate constraint "integrations_user_id_fkey";


