create table if not exists "public"."documents" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "title" text,
    "data" jsonb,
    "type" character varying not null default 'free'::character varying,
    "text" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);


CREATE UNIQUE INDEX IF NOT EXISTS documents_pkey ON public.documents USING btree (id);

alter table "public"."documents" add constraint "documents_pkey" PRIMARY KEY using index "documents_pkey";

alter table "public"."documents" add constraint "documents_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."documents" validate constraint "documents_user_id_fkey";


